import type {Metadata} from 'next';
import '@/styles/globals.css';
import {Public_Sans, Roboto_Mono} from 'next/font/google';

const publicSans = Public_Sans({
	subsets: ['latin'],
	variable: '--font-primary',
});

const robotoMono = Roboto_Mono({
	subsets: ['latin'],
	variable: '--font-mono',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en' className={`${publicSans.variable} ${robotoMono.variable}`}>
			<body>
				<main style={{flex: 1}}>{children}</main>
			</body>
		</html>
	);
}
